<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="288" started-at="2022-06-01T10:42:42Z" finished-at="2022-06-01T10:42:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="288" started-at="2022-06-01T10:42:42Z" finished-at="2022-06-01T10:42:42Z">
      <class name="unittesting.parcijalni.Zadatak3">
        <test-method status="PASS" signature="setUp()[pri:0, instance:unittesting.parcijalni.Zadatak3@215be6bb]" name="setUp" is-config="true" duration-ms="267" started-at="2022-06-01T12:42:42Z" finished-at="2022-06-01T12:42:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testTryPinDoesntMatch()[pri:0, instance:unittesting.parcijalni.Zadatak3@215be6bb]" name="testTryPinDoesntMatch" duration-ms="10" started-at="2022-06-01T12:42:42Z" finished-at="2022-06-01T12:42:42Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
	at unittesting.parcijalni.CreditCardService.tryPIN(CreditCardService.java:78)
	at unittesting.parcijalni.Zadatak3.testTryPinDoesntMatch(Zadatak3.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTryPinDoesntMatch -->
      </class> <!-- unittesting.parcijalni.Zadatak3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
